# Generated by Django 3.0.7 on 2020-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200616_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Kumar', max_length=200, null=True),
        ),
    ]
